// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first_topic.proto

package com.mps.batch_mps_pushdata.proto;

public interface EmployeeEventsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeEvents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Employees employees = 1;</code>
   */
  java.util.List<com.mps.batch_mps_pushdata.proto.Employees> 
      getEmployeesList();
  /**
   * <code>repeated .Employees employees = 1;</code>
   */
  com.mps.batch_mps_pushdata.proto.Employees getEmployees(int index);
  /**
   * <code>repeated .Employees employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .Employees employees = 1;</code>
   */
  java.util.List<? extends com.mps.batch_mps_pushdata.proto.EmployeesOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .Employees employees = 1;</code>
   */
  com.mps.batch_mps_pushdata.proto.EmployeesOrBuilder getEmployeesOrBuilder(
      int index);
}
