// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first_topic.proto

package com.mps.batch_mps_pushdata.proto;

public final class EmployeeListEventWrapper {
  private EmployeeListEventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employees_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employees_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeEvents_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021first_topic.proto\"A\n\tEmployees\022\022\n\nfirs" +
      "t_name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\022\r\n\005email" +
      "\030\003 \001(\t\"/\n\016EmployeeEvents\022\035\n\temployees\030\001 " +
      "\003(\0132\n.EmployeesB>\n com.mps.batch_mps_pus" +
      "hdata.protoB\030EmployeeListEventWrapperP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employees_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employees_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employees_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", });
    internal_static_EmployeeEvents_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmployeeEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeEvents_descriptor,
        new java.lang.String[] { "Employees", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
